apiVersion: apps/v1
kind: Deployment
metadata:
  name:  havells-deployment
  labels:
    name: webdep
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webpod
      app: demo
  template:
    metadata:
      name: webpod
      labels:
        name: webpod
        app: demo
    spec:
      containers:
        - name:  havells-images
          image: 2222s/havells:V-7
          ports:
            - containerPort: 8080
